name: objectdb
description: Persistent embedded document-oriented NoSQL database for Dart and Flutter.
version: 1.1.0-dev+1
homepage: https://github.com/marioreggiori/objectdb
environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
  execution_queue: ^1.0.3
  deeply: ^1.0.1

dev_dependencies:
  test: any
