name: objectdb
description: Persistent embedded document-oriented NoSQL database for Dart and Flutter.
version: 1.0.1
author: Team netz.chat <dev@netzchat.com>
homepage: https://github.com/netz-chat/objectdb
environment:
    sdk: '>=2.0.0-dev.61.0 <3.0.0'

dependencies:
  execution_queue: ^1.0.1
  deeply: ^1.0.0

dev_dependencies:
  test: any
